
title: Sam's Resume
url: 'http://samtang.me'
# baseurl: '/resume-en' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
# style: styles-2
# style: styles-3
# style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Sam Tang
tagline: Bioinformatician
pic: sam.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: tyf@outlook.com
phone: +86 186 2196 9482
website: samtang.me
linkedin: tangyf
github: yftang
twitter: '@yftang'

#Update all the sections by editing the files inside _includes folder.
